from django.db import models

class Tower(models.Model):
    Unique_number = models.IntegerField(unique=True)
    name_tap = models.CharField(max_length=50, blank=True, default="-")
    number_support = models.IntegerField(unique=True)
    VL = models.CharField(max_length=100, default="-")
    type_support = models.CharField(max_length=50)
    code_support = models.CharField(max_length=50, blank=True, default="Не определен")
    material = models.CharField(max_length=50)
    corner = models.FloatField()
    X = models.FloatField()
    Y = models.FloatField()
    Z = models.FloatField()
    shirota = models.FloatField()
    dolgota = models.FloatField()
    height = models.FloatField()
    TPV_photo = models.CharField(max_length=50, blank=True, default="-")
    UF_photo = models.CharField(max_length=50, blank=True, default="-")
    photo = models.CharField(max_length=50, blank=True, default="-")
    v_defects = models.CharField(max_length=10000, blank=True, default="-")
    u_defects = models.CharField(max_length=100, blank=True, default="-")
    code_support_in_1C = models.CharField(max_length=200, blank=True, default="-")
    guid = models.IntegerField(blank=True, default=0)
    flag_defects = models.BooleanField()
    comment_in_TOiR = models.CharField(max_length=100, blank=True, default="-")
    geometry = models.CharField(max_length=100, blank=True, default="-")